### PR TITLE
Resolve naming inconsistencies and update configurations

### PR DESCRIPTION
**Pull request by elix1er**
# Description:
This PR addresses naming inconsistencies across the project and updates various configurations:

- Standardize binary name
- Unify chain IDs
- Consolidate token denomination
- Update Dockerfile to reflect standardized naming
- Modify scripts, tests, and documentation for consistency
- Upgrade CW20 contract version to v2.0.0
- Add new exclusions to .gitignore
- Update README and statesync instructions for testnet

Key changes:

- .gitignore: Add new exclusions for test and contract files
- Dockerfile: Update binary name and build flags
- scripts/: Modify all scripts to use standardized binary and token names
- testnets/: Update README and statesync instructions
- Various other files: Replace inconsistent naming with standardized terms

This standardization effort ensures consistency across the codebase, improves project coherence, and prepares for the upcoming testnet launch.

Please review before merge - ./scripts/**.sh tests not yet working, running due to:

`File at mytestnet/config/genesis.json is a valid genesis file`

ending up with 

```bash

6:54PM ERR CONSENSUS FAILURE!!! err="runtime error: invalid memory address or nil pointer dereference" module=consensus stack="goroutine 202 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x64\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/cometbft/cometbft@v0.38.9/consensus/state.go:801 +0x44\npanic({0x1066cfe20?, 0x108866d50?})\n\truntime/panic.go:770 +0x124\ncosmossdk.io/store/rootmulti.(*Store).GetKVStore(0x14002048200, {0x0, 0x0})\n\tcosmossdk.io/store@v1.1.0/rootmulti/store.go:652 +0x24c\ngithub.com/cosmos/cosmos-sdk/types.Context.KVStore({{0x106c2c408, 0x108a7a0c0}, {0x106c49c80, 0x14002048200}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.7/types/context.go:337 +0x3c\ngithub.com/cosmos/cosmos-sdk/x/params/types.Subspace.kvStore(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.7/x/params/types/subspace.go:77\ngithub.com/cosmos/cosmos-sdk/x/params/types.Subspace.Has({{_, _}, _, {_, _}, {_, _}, {_, _, _}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.7/x/params/types/subspace.go:156 +0xac\ngithub.com/cosmos/cosmos-sdk/baseapp.GetConsensusParams({{0x106c2c408, 0x108a7a0c0}, {0x106c49c80, 0x14002048200}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.7/baseapp/params_legacy.go:117 +0x90\ngithub.com/cosmos/cosmos-sdk/baseapp.MigrateParams({{0x106c2c408, 0x108a7a0c0}, {0x106c49c80, 0x14002048200}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.7/baseapp/params_legacy.go:142 +0x58\ngithub.com/HyperiaNetwork/hyperia/app.(*HyperiaApp).FinalizeBlock.func1()\n\tgithub.com/HyperiaNetwork/hyperia/app/app.go:1077 +0x350\nsync.(*Once).doSlow(0x140026ca328?, 0x10303494c?)\n\tsync/once.go:74 +0x100\nsync.(*Once).Do(...)\n\tsync/once.go:65\ngithub.com/HyperiaNetwork/hyperia/app.(*HyperiaApp).FinalizeBlock(0x14002abc008, 0x140026c3e00)\n\tgithub.com/HyperiaNetwork/hyperia/app/app.go:1069 +0x58\ngithub.com/cosmos/cosmos-sdk/server.cometABCIWrapper.FinalizeBlock(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.50.7/server/cmt_abci.go:44\ngithub.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0x10304f620?, {0x106c2ce50?, 0x108a7a0c0?}, 0x111128180?)\n\tgithub.com/cometbft/cometbft@v0.38.9/abci/client/local_client.go:185 +0xe8\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0x14000f55128, {0x106c2ce50, 0x108a7a0c0}, 0x140026c3e00)\n\tgithub.com/cometbft/cometbft@v0.38.9/proxy/app_conn.go:104 +0x130\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).applyBlock(_, {{{0xb, 0x0}, {0x14001eacafa, 0x6}}, {0x14001eacb10, 0x7}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cometbft/cometbft@v0.38.9/state/execution.go:224 +0x410\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyVerifiedBlock(...)\n\tgithub.com/cometbft/cometbft@v0.38.9/state/execution.go:202\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0x1400155b508, 0x1)\n\tgithub.com/cometbft/cometbft@v0.38.9/consensus/state.go:1772 +0x97c\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0x1400155b508, 0x1)\n\tgithub.com/cometbft/cometbft@v0.38.9/consensus/state.go:1682 +0x26c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\tgithub.com/cometbft/cometbft@v0.38.9/consensus/state.go:1617 +0x8c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0x1400155b508, 0x1, 0x0)\n\tgithub.com/cometbft/cometbft@v0.38.9/consensus/state.go:1655 +0xac4\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0x1400155b508, 0x14000546270, {0x0, 0x0})\n\tgithub.com/cometbft/cometbft@v0.38.9/consensus/state.go:2335 +0x1858\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0x1400155b508, 0x14000546270, {0x0?, 0x103098960?})\n\tgithub.com/cometbft/cometbft@v0.38.9/consensus/state.go:2067 +0x28\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0x1400155b508, {{0x106bf6060, 0x14000c76180}, {0x0, 0x0}})\n\tgithub.com/cometbft/cometbft@v0.38.9/consensus/state.go:929 +0x300\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0x1400155b508, 0x0)\n\tgithub.com/cometbft/cometbft@v0.38.9/consensus/state.go:856 +0x370\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 1\n\tgithub.com/cometbft/cometbft@v0.38.9/consensus/state.go:398 +0xf0\n"

```

## Summary by CodeRabbit

- **New Features**
  - Transition from the "Eve" network to the "Hyperia" network with updated commands, paths, and configurations.
  - Updated testnet documentation to reflect the new network setup.

- **Bug Fixes**
  - Improved error handling and logging in the `FinalizeBlock` method.

- **Style**
  - Standardized token denominations to "uhype" across scripts and tests.

- **Chores**
  - Added specific files and directories to `.gitignore` for improved git management.
  - Updated Dockerfile to reflect new binary name and version details.

### CODE REVIEW

**Comment by elix1er** [comment]
@coderabbitai review

**Comment by faddat** [comment]
Did you resolve the issue with Genesis?

**Comment by elix1er** [comment]
ill hop on it again quick, maybe some plain default genesis file does the job

**Comment by elix1er** [comment]
w8 i got a hint what it could be

**Comment by elix1er** [comment]
i mean, the node starts running now, patched the function in app.go

```go
func (app *HyperiaApp) FinalizeBlock(req *abci.RequestFinalizeBlock) (*abci.ResponseFinalizeBlock, error) {
```

to not fire a panic anymore - but firing following errors:

```bash
4:27AM INF Attempting to migrate consensus parameters error="rpc error: code = Internal desc = collections: not found: key 'no_key' of type github.com/cosmos/gogoproto/tendermint.types.ConsensusParams" module=server
4:27AM ERR baseAppLegacySS is invalid module=server
```

... not sure if that is a good or bad sign

Screenshot 2024-07-09 at 04 29 34


ref: https://github.com/cosmos/cosmos-sdk/issues/20160

**Comment by elix1er** [comment]
i mean, check this:

https://pkg.go.dev/github.com/cosmos/cosmos-sdk/baseapp#pkg-overview


> Deprecated.
> 
> Legacy types are defined below to aid in the migration of CometBFT consensus parameters from use of the now deprecated x/params modules to a new dedicated x/consensus module.
> 
> Application developers should ensure that they implement their upgrade handler correctly such that app.ConsensusParamsKeeper.Set() is called with the values returned by GetConsensusParams().

Example:

```go

baseAppLegacySS := app.ParamsKeeper.Subspace(baseapp.Paramspace).WithKeyTable(paramstypes.ConsensusParamsKeyTable())

app.UpgradeKeeper.SetUpgradeHandler(
	UpgradeName,
	func(ctx sdk.Context, plan upgradetypes.Plan, fromVM module.VersionMap) (module.VersionMap, error) {
		if cp := baseapp.GetConsensusParams(ctx, baseAppLegacySS); cp != nil {
			app.ConsensusParamsKeeper.Set(ctx, cp)
		} else {
			ctx.Logger().Info("warning: consensus parameters are undefined; skipping migration", "upgrade", UpgradeName)
		}

		return app.ModuleManager.RunMigrations(ctx, app.Configurator(), fromVM)
	},
)
```
Developers can also bypass the use of the legacy Params subspace and set the values to app.ConsensusParamsKeeper.Set() explicitly.

**`Note, for new chains this is not necessary as CometBFT's consensus parameters will automatically be set for you in InitChain.`**

Node Log:

```jsonl
{"level":"info","module":"server","error":"rpc error: code = Internal desc = collections: not found: key 'no_key' of type github.com/cosmos/gogoproto/tendermint.types.ConsensusParams","time":"2024-07-09T08:53:41+07:00","message":"Attempting to migrate consensus parameters"}
{"level":"error","module":"server","time":"2024-07-09T08:53:41+07:00","message":"baseAppLegacySS is invalid"}
```

**Comment by elix1er** [comment]
great, wasm test passing - but does anyone know a fix for this annoying logspam with
`service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation` ?

```bash
❯ ./scripts/wasm/test_wasm.sh
Starting chain...
Wasm file already exists for cw20_base
Uploading contract...
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
gas estimate: 2784050
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: C6E838ED45BAAE1F571FBAF376C4973E51AF105848E54BE2D3404C9CFEBD7121
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
code_infos: []
pagination:
  next_key: null
  total: "0"
Instantiating contract...
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation

- address: hype12lzflhjry5mkh03x5200mkwqgk32lxutqpmem7
  name: demo
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AmCiqZBD3JI/ehN00k8WJZTToK0zzfDmfG1ASynA7+rW"}'
  type: local


**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

betray plunge alert aspect stomach bicycle road believe write goddess inherit legal chaos image merit point able suffer combine expire hospital chronic title left
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
gas estimate: 274111
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: C4FB22F606573D97AB68883CA105013C89B2B610741F6E6BCF34A99C7A2EE19C
Waiting for tx to be processed...
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
Validator Balance:
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
data:
  balance: "123456789000"
Demo Balance:
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
data:
  balance: "0"
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
gas estimate: 215246
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: 8D0B84A6B8729B9189CCABE25463CAF69152F0DD72B92DAF6F80978BF05259C4
Waiting for tx to be processed...
Validator Balance:
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
data:
  balance: "122469134679"
Demo Balance:
service alliance.alliance.Msg does not have cosmos.msg.v1.service proto annotation
data:
  balance: "987654321"
Success executing basic wasm tests!
~/Documents/GitHub/hyperia feat--hyperiad* 1m 11s                                                                                                                                                         09:48:44 AM
❯ 
```

**Comment by elix1er** [comment]
probably gonna redo this PR in smaller steps, rather than as it's current state, fyi

**Comment by faddat** [comment]
Hey, actually this is pretty good and thank you. I'm going to live through it I'll probably push to your door but I'll be using your commits. thank you so much

**Pull request merged**
